import { PrismaClient, BadgeCategory, BadgeRarity } from '@prisma/client';

const prisma = new PrismaClient();

const badges = [
  {
    slug: 'first-bet',
    name: 'First Bet',
    description: 'Placed your first bet',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.COMMON,
    trigger: 'totalBets',
    threshold: 1,
    xpReward: 50,
    sortOrder: 1,
  },
  {
    slug: 'ten-bets',
    name: 'Getting Started',
    description: 'Placed 10 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.COMMON,
    trigger: 'totalBets',
    threshold: 10,
    xpReward: 100,
    sortOrder: 2,
  },
  {
    slug: 'fifty-bets',
    name: 'Regular',
    description: 'Placed 50 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.UNCOMMON,
    trigger: 'totalBets',
    threshold: 50,
    xpReward: 250,
    sortOrder: 3,
  },
  {
    slug: 'hundred-bets',
    name: 'Centurion',
    description: 'Placed 100 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.RARE,
    trigger: 'totalBets',
    threshold: 100,
    xpReward: 500,
    sortOrder: 4,
  },
  {
    slug: 'five-hundred-bets',
    name: 'Veteran',
    description: 'Placed 500 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.EPIC,
    trigger: 'totalBets',
    threshold: 500,
    xpReward: 1000,
    sortOrder: 5,
  },
  {
    slug: 'first-win',
    name: 'Winner',
    description: 'Won your first bet',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.COMMON,
    trigger: 'totalWins',
    threshold: 1,
    xpReward: 50,
    sortOrder: 10,
  },
  {
    slug: 'ten-wins',
    name: 'On a Roll',
    description: 'Won 10 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.UNCOMMON,
    trigger: 'totalWins',
    threshold: 10,
    xpReward: 200,
    sortOrder: 11,
  },
  {
    slug: 'fifty-wins',
    name: 'Sharpshooter',
    description: 'Won 50 bets',
    category: BadgeCategory.MILESTONE,
    rarity: BadgeRarity.RARE,
    trigger: 'totalWins',
    threshold: 50,
    xpReward: 500,
    sortOrder: 12,
  },
  {
    slug: 'streak-3',
    name: 'Hot Hand',
    description: '3 wins in a row',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.UNCOMMON,
    trigger: 'bestStreak',
    threshold: 3,
    xpReward: 100,
    sortOrder: 20,
  },
  {
    slug: 'streak-5',
    name: 'On Fire',
    description: '5 wins in a row',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.RARE,
    trigger: 'bestStreak',
    threshold: 5,
    xpReward: 200,
    sortOrder: 21,
  },
  {
    slug: 'streak-10',
    name: 'Unstoppable',
    description: '10 wins in a row',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.EPIC,
    trigger: 'bestStreak',
    threshold: 10,
    xpReward: 500,
    sortOrder: 22,
  },
  {
    slug: 'high-roller',
    name: 'High Roller',
    description: 'Wagered over 1 ETH total',
    category: BadgeCategory.VOLUME,
    rarity: BadgeRarity.RARE,
    trigger: 'totalVolume',
    threshold: 1_000_000_000_000_000_000,
    xpReward: 200,
    sortOrder: 30,
  },
  {
    slug: 'whale',
    name: 'Whale',
    description: 'Wagered over 10 ETH total',
    category: BadgeCategory.VOLUME,
    rarity: BadgeRarity.EPIC,
    trigger: 'totalVolume',
    threshold: 10_000_000_000_000_000_000,
    xpReward: 1000,
    sortOrder: 31,
  },
  {
    slug: 'diamond-hands',
    name: 'Diamond Hands',
    description: 'Wagered over 50 ETH total',
    category: BadgeCategory.VOLUME,
    rarity: BadgeRarity.LEGENDARY,
    trigger: 'totalVolume',
    threshold: 50_000_000_000_000_000_000,
    xpReward: 2500,
    sortOrder: 32,
  },
  {
    slug: 'beta-tester',
    name: 'Beta Tester',
    description: 'Participated in the beta phase',
    category: BadgeCategory.MANUAL,
    rarity: BadgeRarity.RARE,
    trigger: 'manual',
    threshold: 0,
    xpReward: 100,
    sortOrder: 50,
  },
  {
    slug: 'early-player',
    name: 'Early Player',
    description: 'Joined during the early days',
    category: BadgeCategory.MANUAL,
    rarity: BadgeRarity.UNCOMMON,
    trigger: 'manual',
    threshold: 0,
    xpReward: 50,
    sortOrder: 51,
  },
  {
    slug: 'verified',
    name: 'Verified',
    description: 'Verified community member',
    category: BadgeCategory.MANUAL,
    rarity: BadgeRarity.EPIC,
    trigger: 'manual',
    threshold: 0,
    xpReward: 0,
    sortOrder: 52,
  },
  {
    slug: 'founder',
    name: 'Founder',
    description: 'Rush founding member',
    category: BadgeCategory.MANUAL,
    rarity: BadgeRarity.LEGENDARY,
    trigger: 'manual',
    threshold: 0,
    xpReward: 500,
    sortOrder: 53,
  },
];

async function main() {
  console.log('Seeding badge definitions...');

  for (const badge of badges) {
    await prisma.badge.upsert({
      where: { slug: badge.slug },
      update: {
        name: badge.name,
        description: badge.description,
        category: badge.category,
        rarity: badge.rarity,
        trigger: badge.trigger,
        threshold: badge.threshold,
        xpReward: badge.xpReward,
        sortOrder: badge.sortOrder,
      },
      create: badge,
    });
    console.log(`  Badge: ${badge.slug}`);
  }

  console.log(`Seeded ${badges.length} badges.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
